# Default BootGuard Configurations

# File Loader (directories to ignore from scanning)
ignore.directories=.git,target,node_modules,build,dist,.idea

# Secret Detection Configurations
secret.min.length=8
metric.entropy.threshold=0.75
metric.entropy.high.threshold=0.85
secret.keyword.pattern=(?i)(password|secret|key|token|api|auth|credential|private|signing|jwt|pat|bearer)
secret.provider.pattern=^(ghp_[a-zA-Z0-9]{36}|AKIA[A-Z0-9]{16}|xox[baprs]-[0-9]{10,13}-[a-zA-Z0-9]{24}|sk_live_[a-zA-Z0-9]{24})$

# H2 Console
h2.weak.passwords=password,root,admin

# VCS / GitIgnore Check
sensitive.files.pattern=-prod.yml,-prod.yaml,-prod.properties,.env
